name: Cargo check

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup protoc
        run: |
          sudo apt-get install protobuf-compiler

      - name: Run cargo check
        run: |
          cd api/
          cargo check
