name: Deploy Rust API

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
